name: 'msw'
description: 'run msw action'
runs:
  using: 'composite'
  steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - name: Set up node
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Detect changes in mockServiceWorker.js
        run: |
          # Check for changes in the specific file
          if git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep -q '^public/mockServiceWorker.js$'; then
            echo "Changes detected in public/mockServiceWorker.js"
            exit 1
          else
            echo "No changes detected in public/mockServiceWorker.js"
          fi
        shell: bash

      - name: Install node_modules
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: npm ci
        shell: bash

      - name: Regenerate mockServiceWorker.js
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: |
          # git config pull.rebase false

          git fetch origin
          git checkout $CURRENT_BRANCH_NAME
          git merge origin/master || {
            echo "Merge conflict detected. Resolve manually.";
            exit 1;
          }
          npx msw init public/ --save
        shell: bash

      - name: Check for changes in mockServiceWorker.js
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: |
          if [[ $(git status --porcelain) ]]; then
            git status --porcelain
            git add .
            git commit --no-verify -m "[dependabot skip] Automatically updatiing mockServiceWorker.js file after 'msw' update in package.json"
            git push origin $CURRENT_BRANCH_NAME
          else
            echo "No changes in mockServiceWorker.js"
          fi   
        shell: bash
    