name: 'msw'
description: 'run msw action'
runs:
  using: 'composite'
  steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - name: Set up node
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Detect changes in mockServiceWorker.js
        run: |
          # Check for changes in the specific file
          if git diff --name-only origin/${{ github.event.pull_request.head.ref }}...HEAD | grep -q '^public/mockServiceWorker.js$'; then
            echo "Changes detected in public/mockServiceWorker.js"
            exit 1
          else
            echo "No changes detected in public/mockServiceWorker.js"
          fi
        shell: bash

      - name: Install node_modules
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: npm ci
        shell: bash   

      - name: Regenerate mockServiceWorker.js
        if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: |
          echo "Current branch is: $(git rev-parse --abbrev-ref HEAD)"
          git config pull.rebase false      
          git pull origin ${{ github.event.pull_request.head.ref }} --allow-unrelated-histories
          git checkout ${{ github.event.pull_request.head.ref }}
          npx msw init public/ --save
        shell: bash
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: GitHub
          GIT_COMMITTER_EMAIL: actions@github.com

      - name: Check for changes in mockServiceWorker.js
        if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: GitHub
          GIT_COMMITTER_EMAIL: actions@github.com
        shell: bash
        run: |
          if [[ $(git status --porcelain) ]]; then
            git status --porcelain
            git add .
            git commit -m "[dependabot skip] Automatically updatiing mockServiceWorker.js file after 'msw' update in package.json"  
            git push 
          else
            echo "No changes in mockServiceWorker.js"
          fi