name: custom

on:
  workflow_dispatch: # Allows manual trigger of the workf

env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub
  GIT_COMMITTER_EMAIL: actions@github.com

permissions:
  contents: write
  pull-requests: write

jobs:
  check_dependabot_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Create new PR for msw bump
        run: |
          echo "Bla Bla"
          echo ":alert: :alert: :alert: The patching of resources failed during deployment! GitHub repository: $(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2) Link to GHA: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"