name: msw

on:  
  pull_request:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.PAT_TOKEN }}
  # GIT_AUTHOR_NAME: ${{ github.actor }}
  # GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
  # GIT_COMMITTER_NAME: GitHub
  # GIT_COMMITTER_EMAIL: actions@github.com
  # BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  #BRANCH_NAME: msw-update-${{ github.run_id }}

jobs:
  update_msw_worker:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - uses: actions/checkout@v4 

      - name: Authenticate with PAT
        run: |
          echo ${{ secrets.PAT_TOKEN }} | gh auth login --with-token
          # echo "$GH_TOKEN" | gh auth login --with-token

      - name: Set up node
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install node_modules
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: npm ci
      
      - name: Find Dependabot PR for msw
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # PR_ID=$(gh pr list --head ${{ github.event.pull_request.head.ref }} --json url --jq ".[0].url")
          PR_URL=$(gh pr list --search "dependabot update msw" --json url --jq ".[0].url")
          # PR_ID=$(gh pr list ${{ github.event.pull_request.head.ref }} --json id --jq ".[0].id")
          echo "PR_URL=${PR_URL}" >> $GITHUB_ENV

      - name: Create new PR for msw bump
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: |
          gh pr checkout "${PR_URL}"
          git checkout -b new-msw-bump
          npx msw init public/ --save
          git add .
          git commit --no-verify -m "[dependabot skip] Automatically updatiing mockServiceWorker.js file after 'msw' update in package.json"
          git push origin new-msw-bump --force
          gh pr create \
            --title "Bump msw to latest version" \
            --body "This PR is based on the Dependabot bump for the MSW library with updates in mockServiceWorker.js file" \
            --base master \
            --head new-msw-bump

      - name: Close msw bump from Dependabot
        if: ${{ contains(steps.dependabot-metadata.outputs.dependency-names, 'msw') }}
        run: |
          gh pr close "${PR_URL}"